# Generated by Django 3.2.8 on 2021-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=511, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.PositiveIntegerField()),
                ('company_bills_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('company_code', models.CharField(max_length=200, unique=True)),
                ('vat_required', models.BooleanField(default=1)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='product/image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=511, unique=True)),
                ('parking', models.BooleanField(default=True)),
                ('free_wifi', models.BooleanField(default=True)),
                ('with_kitchen', models.BooleanField(default=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('store_location', models.CharField(max_length=30)),
                ('franchise', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.ourclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='store.store')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
    ]
