# Generated by Django 3.2.8 on 2021-12-16 05:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=511, unique=True)),
                ('country', models.CharField(default='Nepal', max_length=255)),
                ('street_address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.PositiveIntegerField()),
                ('company_bills_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('company_code', models.CharField(max_length=200, unique=True)),
                ('vat_required', models.BooleanField(default=1)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='product/image')),
            ],
            options={
                'verbose_name': 'Comany',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=511, unique=True)),
                ('parking', models.BooleanField(default=True)),
                ('free_wifi', models.BooleanField(default=True)),
                ('with_kitchen', models.BooleanField(default=True)),
                ('country', models.CharField(default='Nepal', max_length=255)),
                ('street_address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=255)),
                ('contact_number', models.CharField(max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('franchise', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='store.store')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
    ]
