# Generated by Django 3.2.8 on 2021-11-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_location',
        ),
        migrations.AddField(
            model_name='ourclient',
            name='country',
            field=models.CharField(default='Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='postal_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='street_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='street_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ourclient',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
