# Generated by Django 3.2.8 on 2021-12-16 05:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general', 'general'), ('regular', 'regular'), ('staff', 'staff'), ('ncell', 'ncell'), ('vip', 'vip')], default='general', max_length=31)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('discount_cap', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object modified date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created date and time')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], default='Male', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('customer_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customertier')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
