# Generated by Django 3.2.8 on 2021-11-28 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='effictive_date',
        ),
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Object created date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Object modified date and time'),
        ),
    ]
