# Generated by Django 3.2.8 on 2021-12-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object modified date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created date and time')),
                ('bill_number', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('order_status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Created', max_length=100)),
                ('processed_by', models.CharField(blank=True, default='', max_length=255)),
                ('order_type', models.CharField(choices=[('Dine-in', 'Dine-in'), ('Take-away', 'Take-away')], default='Ordered', max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('taxable_amount', models.PositiveIntegerField(default=0)),
                ('tax_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_refund_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('table_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object modified date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created date and time')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('sub_total', models.PositiveIntegerField()),
                ('reedem', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
